services:
  database:
    image: postgres:18.0-alpine3.22
    container_name: task_list_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_list_database
    restart: no
    ports:
      - "5432:5432"
    networks:
      - task_list_network
    volumes:
      - task_list_volume_database:/var/lib/postgresql/18/docker
volumes:
  task_list_volume_database:
networks:
  task_list_network:
    driver: bridge

